const mockExpenses = [
  {
    id: "1",
    amount: "50.00",
    category: "Groceries",
    emoji: "🛒",
    date: "2025-05-15",
    note: "Weekly grocery shopping",
  },
  {
    id: "2",
    amount: "20.00",
    category: "Transport",
    emoji: "🚗",
    date: "2025-05-14",
    note: "Bus fare",
  },
  {
    id: "3",
    amount: "30.00",
    category: "Dining",
    emoji: "🍕",
    date: "2025-05-13",
    note: "Dinner with friends",
  },
  {
    id: "4",
    amount: "15.00",
    category: "Entertainment",
    emoji: "🎥",
    date: "2025-05-12",
    note: "Movie ticket",
  },
  {
    id: "5",
    amount: "100.00",
    category: "Shopping",
    emoji: "🛍️",
    date: "2025-05-11",
    note: "Clothes shopping",
  },
  {
    id: "6",
    amount: "10.00",
    category: "Snacks",
    emoji: "🍿",
    date: "2025-05-10",
    note: "Evening snacks",
  },
  {
    id: "7",
    amount: "200.00",
    category: "Rent",
    emoji: "🏠",
    date: "2025-05-01",
    note: "Monthly rent payment",
  },
  {
    id: "8",
    amount: "25.00",
    category: "Utilities",
    emoji: "💡",
    date: "2025-05-05",
    note: "Electricity bill",
  },
  {
    id: "9",
    amount: "40.00",
    category: "Fitness",
    emoji: "🏋️",
    date: "2025-05-07",
    note: "Gym membership",
  },
  {
    id: "10",
    amount: "5.00",
    category: "Miscellaneous",
    emoji: "📎",
    date: "2025-05-09",
    note: "Stationery items",
  },
];

export default mockExpenses;
